In [2]:
import numpy as np

In [3]:
arr1 = np.arange(20,26,2)
arr1
print(arr1) #printing array1 with print might cause cinfuison wheter it is a list or array

[20 22 24]


In [14]:
arr1 =np.arange(10000)
arr1 ##...... will be displayed to print function limitation to overcome this

import sys
np.set_printoptions(threshold=sys.maxsize)
arr2 =np.arange(10000)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr2 =np.arange(100).reshape(5,20)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

# Reshaping Array

In [24]:
arr3=np.arange(30).reshape(6,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [31]:
arr4 = np.arange(100).reshape(-1,20)#corrensponding row or column number will be calulated automatically if -1 is used
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [33]:
arr5 = np.array(['AP','PR','QR','CK','GT','LM','NK','NA','LO','SQ','AR','BP'])
arr5 #U2 string object data type representation in numpy array

array(['AP', 'PR', 'QR', 'CK', 'GT', 'LM', 'NK', 'NA', 'LO', 'SQ', 'AR',
       'BP'], dtype='<U2')

In [35]:
arr5.reshape(4,-1).T #Transpose of a matrix 4X3 to 3X4 here

array([['AP', 'CK', 'NK', 'SQ'],
       ['PR', 'GT', 'NA', 'AR'],
       ['QR', 'LM', 'LO', 'BP']], dtype='<U2')

In [37]:
np.reshape(arr5,(4,-1),order='C') #Row wise fill or also known as Row Major Form

array([['AP', 'PR', 'QR'],
       ['CK', 'GT', 'LM'],
       ['NK', 'NA', 'LO'],
       ['SQ', 'AR', 'BP']], dtype='<U2')

In [39]:
np.reshape(arr5,(4,-1),order='F')#Column wise fill or also known as column major form

array([['AP', 'GT', 'LO'],
       ['PR', 'LM', 'SQ'],
       ['QR', 'NK', 'AR'],
       ['CK', 'NA', 'BP']], dtype='<U2')

# Basic Operations

In [45]:
arr1=np.array([10,20,30,40,50])
print(arr1+2)
print(arr1*2)#Scalar product
print(arr1%2)
print(arr1**2)
print(arr1>30)
#Functions
np.sqrt(arr1)
np.log(arr1)
np.sin(arr1*np.pi/180)


[12 22 32 42 52]
[ 20  40  60  80 100]
[0 0 0 0 0]
[ 100  400  900 1600 2500]
[False False False  True  True]


array([0.17364818, 0.34202014, 0.5       , 0.64278761, 0.76604444])

In [50]:
#Dot product of matrix

arr1=np.array([[10,20],[30,40]])
arr2=np.array([[30,30],[20,20]])
arr1.dot(arr2)


array([[ 700,  700],
       [1700, 1700]])

In [72]:
#To modify existing array
arr1=np.array([[10,20],[30,40]])
arr2=np.array([[30,30],[20,20]])
arr1 =arr1.dot(arr2)
arr1

array([[ 700,  700],
       [1700, 1700]])

In [54]:
#unary Operations - sum,max,min
np.sum(arr2)
np.max(arr2)
np.min(arr2)


20

In [63]:
arr5=np.arange(25,50).reshape(5,-1)
arr5

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [67]:
#Sum along row wise or column wise
np.sum(arr5,axis = 1) #rowwise
np.sum(arr5,axis=0)#columnwise

array([175, 180, 185, 190, 195])

In [69]:
#max along column or row wise
np.max(arr5,axis=1)
#similary of 

array([29, 34, 39, 44, 49])

# Universal Functions

In [4]:
#add
#multiply,radian ,sin,cos and many print(dir(np)) to know all the different methods
arr1=np.array([[10,20],[20,30]])
arr2=np.array([[10,20],[20,30]])

In [5]:
print(np.add(arr1,arr2))

[[20 40]
 [40 60]]


In [7]:
print(np.multiply(arr1,arr2))
#print(dir(np))

[[100 400]
 [400 900]]


# Brodacasting

In [ ]:
#Atleast one array should be of single dimension
#No.of elements in single dimension array and no of columns in multi dimensinal array should be same - Row wise broad casting

#Ex-1X5 broadcasting with 6X5 is possible and the resultant matrix will be 6X5

#5X1 broadcasting with 6X5 is possible and the resultant will be 6X1 so 6X5 and 5X1 will form a 6

General Principle:



In [38]:
arr1=np.arange(30).reshape(6,-1)
print(arr1.shape) 
arr2=np.arange(6).reshape(6,1)
print(arr2.shape)
arr2

(6, 5)
(6, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Statistical Functions

In [ ]:
# # mean,median,Standar deviation, variance ,, can be performed on arrays

# np.mean(arr1)
# np.std()
# np.var()

# Indexing and Slicing

In [ ]:
#Array Supports positive and negatiev indexing

In [3]:
arr1=np.arange(20,26)
arr1


array([20, 21, 22, 23, 24, 25])

In [4]:
#I-d Array
#Indexing
print(arr1[0])
print(arr1[-1])
print(arr1[2])

#Slicinig

print(arr1[::])
print(arr1[::-1])
print(arr1[::2])
print(arr1[-2:-5:-2])

20
25
22
[20 21 22 23 24 25]
[25 24 23 22 21 20]
[20 22 24]
[24 22]


In [57]:
#2-D array
arr1 = np.arange(25,50).reshape(5,-1)
arr1.shape
arr1

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [59]:
#Indexing
arr1[2]
arr1[2][2]
arr1[2,2]
#But for acessing whole column we have to go with slicing


37

In [77]:
arr1[:,2:3] # all rows,from start to stop range of columns
arr1[2:4,2:4]
arr1[0:5:2,2:5:2]

array([[27, 29],
       [37, 39],
       [47, 49]])